from datetime import datetime, timezone
from typing import Any, Dict, List
from app.observability.tracer import tracer


def format_personalized_newsletter(
    customer_profile: Dict[str, Any],
    curated_items: List[Dict[str, Any]],
    output_format: str = "markdown"
) -> Dict[str, Any]:
    """Formats curated release notes into an executive-ready personalized customer newsletter.
    
    Args:
        customer_profile: Customer metadata dictionary.
        curated_items: Ranked and scored release notes items.
        output_format: Desired format ('markdown' or 'html'). Defaults to 'markdown'.
        
    Returns:
        A dictionary containing the title, raw content, summary, and metadata.
    """
    with tracer.trace_span("format_personalized_newsletter", {"customer": customer_profile.get("name"), "format": output_format}):
        customer_name = customer_profile.get("name", "Valued Customer")
        industry = customer_profile.get("industry", "Enterprise")
        priorities = ", ".join(customer_profile.get("priorities", ["Cloud Innovation"]))
        current_date = datetime.now(timezone.utc).strftime("%B %d, %Y")
        
        high_items = [i for i in curated_items if i.get("relevance_score") == "High"]
        med_items = [i for i in curated_items if i.get("relevance_score") == "Medium"]
        
        title = f"Google Cloud & Gemini Enterprise Digest for {customer_name}"
        
        lines = [
            f"# {title}",
            f"**Prepared for:** {customer_name} ({industry})  ",
            f"**Focus Areas:** {priorities}  ",
            f"**Edition:** {current_date}  ",
            "",
            "---",
            "",
            "## 📌 Executive Summary",
            (
                f"Welcome to your tailored Google Cloud update. This edition filters recent platform announcements "
                f"specifically for {customer_name}'s architecture and current priorities ({priorities}). "
                f"We have highlighted **{len(high_items)} critical update(s)** requiring immediate architectural attention "
                f"and **{len(med_items)} operational enhancement(s)** relevant to your engineering roadmaps."
            ),
            "",
            "---",
            "",
            "## 🚀 High-Priority Updates (Direct Strategic Impact)",
            ""
        ]
        
        if not high_items:
            lines.append("_No critical breaking changes or direct-match features in this release cycle._")
            lines.append("")
        else:
            for item in high_items:
                rn = item["release_note"]
                status_badge = f"🟢 **{rn.get('status_type', 'GA')}**" if rn.get('status_type') == 'GA' else f"🟡 **{rn.get('status_type', 'Preview')}**"
                lines.extend([
                    f"### {status_badge} [{rn.get('title')}]({rn.get('url')})",
                    f"- **Date:** {rn.get('date')}",
                    f"- **Category:** {rn.get('category')}",
                    f"- **Summary:** {rn.get('summary')}",
                    f"- **💡 Why It Matters to {customer_name}:** {item.get('why_it_matters')}",
                    f"- **🎯 Recommended Next Step:** `{item.get('recommended_action')}`",
                    ""
                ])
                
        lines.extend([
            "---",
            "",
            "## ⚙️ Relevant Operational & Platform Updates",
            ""
        ])
        
        if not med_items:
            lines.append("_No secondary platform updates for this cycle._")
            lines.append("")
        else:
            for item in med_items:
                rn = item["release_note"]
                status_badge = f"🟢 **{rn.get('status_type', 'GA')}**" if rn.get('status_type') == 'GA' else f"🟡 **{rn.get('status_type', 'Preview')}**"
                lines.extend([
                    f"### {status_badge} [{rn.get('title')}]({rn.get('url')})",
                    f"- **Category:** {rn.get('category')} | **Date:** {rn.get('date')}",
                    f"- **Impact:** {item.get('why_it_matters')}",
                    f"- **Action:** {item.get('recommended_action')}",
                    ""
                ])
                
        lines.extend([
            "---",
            "",
            "## 📋 Recommended Action Items for Your Team",
            f"1. **Architecture Review**: Evaluate high-priority features with your lead engineers.",
            f"2. **Sandbox Testing**: Test upcoming Preview capabilities in a dedicated dev project.",
            f"3. **Feedback & Questions**: Contact your Google Cloud Account Team or reply directly to this agent.",
            "",
            "> *Generated by the Gemini Enterprise Personalized Newsletter Agent. Grounded on official Google Cloud Release Notes.*"
        ])
        
        newsletter_md = "\n".join(lines)
        
        result = {
            "title": title,
            "content": newsletter_md,
            "high_priority_count": len(high_items),
            "medium_priority_count": len(med_items),
            "customer_name": customer_name,
            "generated_at": current_date,
            "format": output_format
        }
        tracer.info("newsletter_formatted", f"Generated complete newsletter markdown for {customer_name}", length=len(newsletter_md))
        return result
